version: "3.1"
services:
  api-rest:
    build: .
    restart: always
    ports:
      - 8000:${API_PORT}
    env_file:
      - .env
    links:
      - mysql-db
    volumes:
      - .:/home/alonsojl:delegated
    command: make run
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3307:${DB_PORT}
